version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/storage:/var/www/html/public/storage
    depends_on:
      - mysql
      - redis
    networks:
      - chat-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_backend
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chat-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - chat-network

volumes:
  mysql_data:

networks:
  chat-network:
    driver: bridge